{"name": "test_login_failure_002", "status": "passed", "start": 1744076185700, "stop": 1744076185896, "uuid": "3d74fdb6-9e2b-4ee2-b0cd-666c93e3572a", "historyId": "278963ad5241dd457d6f7c44b2e093a8", "testCaseId": "278963ad5241dd457d6f7c44b2e093a8", "fullName": "testplatform.tests.unit.test_Login.TestLogin#test_login_failure_002", "labels": [{"name": "parentSuite", "value": "testplatform.tests.unit"}, {"name": "suite", "value": "test_Login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "HO"}, {"name": "thread", "value": "28800-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testplatform.tests.unit.test_Login"}]}