{"name": "test_login_failure_004", "status": "passed", "start": 1743386890537, "stop": 1743386890720, "uuid": "1eac0bc5-52c8-464c-a964-017de541bd71", "historyId": "9f77d515c78065611c1e8bc731fe5929", "testCaseId": "9f77d515c78065611c1e8bc731fe5929", "fullName": "testplatform.tests.unit.test_Login.TestLogin#test_login_failure_004", "labels": [{"name": "parentSuite", "value": "testplatform.tests.unit"}, {"name": "suite", "value": "test_Login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "HO"}, {"name": "thread", "value": "4584-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testplatform.tests.unit.test_Login"}]}