{"name": "test_login_failure_002", "status": "passed", "start": 1743386890317, "stop": 1743386890502, "uuid": "192bba25-b9b9-474e-af0e-4536164e2c1a", "historyId": "278963ad5241dd457d6f7c44b2e093a8", "testCaseId": "278963ad5241dd457d6f7c44b2e093a8", "fullName": "testplatform.tests.unit.test_Login.TestLogin#test_login_failure_002", "labels": [{"name": "parentSuite", "value": "testplatform.tests.unit"}, {"name": "suite", "value": "test_Login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "HO"}, {"name": "thread", "value": "4584-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testplatform.tests.unit.test_Login"}]}