{"name": "test_register_failure_004", "status": "failed", "statusDetails": {"message": "AssertionError: 405 != 400", "trace": "self = <test_Newregister.TestNewregister testMethod=test_register_failure_004>\n\n        def test_register_failure_004(self):\n            response = requests.get('http://127.0.0.1:8000/home/api/register/', params= { \"username\": \"userfour\",\n      \"email\": \"user.four1@example.com\",\n    })\n>           self.assertEqual(response.status_code, 400)\nE           AssertionError: 405 != 400\n\ntestplatform\\tests\\unit\\test_Newregister.py:38: AssertionError"}, "start": 1743386553027, "stop": 1743386553032, "uuid": "7838f6b2-912f-43c1-b749-284465df9ad0", "historyId": "265f5cf07994eec485e8428059fd8678", "testCaseId": "265f5cf07994eec485e8428059fd8678", "fullName": "testplatform.tests.unit.test_Newregister.TestNewregister#test_register_failure_004", "labels": [{"name": "parentSuite", "value": "testplatform.tests.unit"}, {"name": "suite", "value": "test_Newregister"}, {"name": "subSuite", "value": "TestNewregister"}, {"name": "host", "value": "HO"}, {"name": "thread", "value": "22000-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testplatform.tests.unit.test_Newregister"}]}